### ISSUE TITLE
Demonstrate 'user query to response cycle' on Staging environment

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/DAU#13]
### Overview
1. User sends video or audio to tipline
2. Server receives the media item and adds to queue
3. Workers create signature/vector representation
4. Search for signature 
5. Send Matching article or "Not found" message

### Tickets
- [x] #27
- [x] #28
- [x] #29
- [x] #30
- [x] #31

### Tasks 
- [ ] Check in with Gupshup over process of connecting dau number to their API
- [ ] Check in with Gupshup over whitelisting their IPs [ref](https://docs.gupshup.io/docs/webhook-key-points)

### Acceptance Criteria
- [ ] User can message on DAU number and get auto response when a match is present
