### ISSUE TITLE
Setup a Whatsapp Tipline for Deepfakes

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/DAU#2]
### Features 
- [x] https://github.com/tattle-made/DAU_tipline/issues/1
- [x] #3 
- [x] #13
- [ ] https://github.com/tattle-made/DAU_tipline/issues/21
- [ ] https://github.com/tattle-made/DAU_tipline/issues/23
- [x] #16
- [ ] #14
- [ ] #15
- [ ] #26

#### Security
- [x] https://github.com/tattle-made/security/issues/57
- [x] https://github.com/tattle-made/security/issues/58
