### ISSUE TITLE
Responding to new posts

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/DAU#32]
## User Requests:
- [x] #47
- [x] #48
- [ ] #49
- [x] The DAU team should be able to customize the conversation flows
- [x] https://github.com/tattle-made/DAU/issues/100
- [x] https://github.com/tattle-made/DAU/issues/99
- [x] #104
- [ ] #105

### (Legacy) 

- [x] https://github.com/tattle-made/DAU_tipline/issues/13
- [x] #37
- [x] #41
- [x] #46
