### ISSUE TITLE
Automated replies to repeat posts

### ISSUE THREAD

**Issue by tarunima** [tattle-made/DAU#53]
## User requests

- [ ] #54
- [ ] #55
- [x] https://github.com/tattle-made/dau-dashboard/issues/2
- [x] https://github.com/tattle-made/DAU_tipline/issues/23
- [ ] #89
## Legacy
- [x] https://github.com/tattle-made/DAU_tipline/issues/21

**Comment by dennyabrain** [comment]
Continued to https://github.com/tattle-made/DAU/issues/125
